### ISSUE TITLE
NGS demo code

### ISSUE THREAD

**Issue by mitchshack** [soartech/new-goal-system-4#3]
I'm wondering if there is any complete example demo code available for NGS 4?  The information from Tim Saucer's TankSoar presentation from the 2017 Soar workshop is very helpful, as is Jacob Crossman's presentation on NGS 4 from the same workshop.

In the TankSoar presentation there are several useful snippets of TankSoar NGS code, but I haven't found any end-to-end examples that I can directly run in JSoar, trace through the code, and better understand how the pieces all fit together in the context of a working example.  A working version of TankSoar for NGS, or another example from the CSoar tutorial ported to NGS would be a great start.

**Comment by timsaucer** [comment]
I'm working on putting something together for you right now.

**Comment by mitchshack** [comment]
Thanks Tim.  I very much appreciate you putting your effort into this.  I look forward to trying out the example code whenever it's ready.

**Comment by timsaucer** [comment]
Can you please take a look at https://github.com/soartech/ngs4-tanksoar and let me know if you run into any problems?

**Comment by timsaucer** [comment]
I'm going to close the issue here. I've updated the readme to point to the example. If you have problems with the agent, please feel free to add an issue on that repository.
